apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  USERNAME: "miusuario"

---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  API_KEY: "miapikeysecreta"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-test
  template:
    metadata:
      labels:
        app: backend-test
    spec:
      containers:
        - name: backend-test
          image: localhost:8082/docker-hosted/backend-test:latest
          ports:
            - containerPort: 3000
          env:
            - name: USERNAME
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: USERNAME
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: API_KEY

---
apiVersion: v1
kind: Service
metadata:
  name: backend-test-service
spec:
  selector:
    app: backend-test
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP